server:
  port: 8090
spring:
  application:
    # 用于在Eureka控制中心区分出不同的服务
    name: order-server
  # 配置redis（注意192.168.0.104（也可以使用域名）的redis服务需要事先启动，这里不在演示
  redis:
    port: 6379
    host: 192.168.0.104
    password: sysapl
  cloud:
    loadbalancer:
      retry:
        # 开启重试机制
        enabled: true
        # 对当前实例重试的次数（默认值是0
        max-retries-on-same-service-instance: 1
        # 切换实例重试的次数（默认值是1
        max-retries-on-next-service-instance: 1
        # 对所有操作请求都进行重试
        retry-on-all-operations: true
  zipkin:
    base-url: http://192.168.0.104:9411
  sleuth:
    sampler:
      probability: 1
feign:
  client:
    config:
      # 设置应用程序中每个 Feign Client 的连接和读取超时
      default:
        connectTimeout: 2000
        readTimeout: 2000
  circuitbreaker:
    enabled: true
# 超时时间调整（默认超时是1秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # Hystrix的超时时间需要大于Ribbon（也就是Loadbalancer的超时时间
            # 否则Hystrix命令超时后，该请求直接熔断，重试机制就没有意义了
            # Hystrix超时 > Ribbon超时: (当前实例重试的次数+1)*(切换实例重试的次数+1)*Timeout
            timeoutInMilliseconds: 10000

limitNum: 10
